bit-oasis/coin

src/BitOasis/Coin/Address/BitcoinCashAddress.php, src/BitOasis/Coin/Address/LitecoinAddress.php, src/BitOasis/Coin/LegacyAddress.php, tests/unit/BitOasis/Coin/Address/BitcoinCashAddressTest.php, tests/unit/BitOasis/Coin/Address/LitecoinAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/9)
=> BB-905: Add Legacy Address interface

src/BitOasis/Coin/Address/AlgorandAddress.php, src/BitOasis/Coin/Address/BasicAttentionTokenAddress.php, src/BitOasis/Coin/Address/EthereumAddress.php, src/BitOasis/Coin/Address/OmiseGoAddress.php, src/BitOasis/Coin/Address/TetherAddress.php, src/BitOasis/Coin/Address/Validators/AlgorandAddressValidator.php, src/BitOasis/Coin/Address/ZeroXAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/AlgorandAddressTest.php, tests/unit/BitOasis/Coin/Address/BasicAttentionTokenAddressTest.php, tests/unit/BitOasis/Coin/Address/OmiseGoAddressTest.php, tests/unit/BitOasis/Coin/Address/TetherAddressTest.php, tests/unit/BitOasis/Coin/Address/ZeroXAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/11)
=> BB-1047: Add new tokens

src/BitOasis/Coin/Address/AlgorandAddress.php, src/BitOasis/Coin/Address/BaseBitcoinCashAddress.php, src/BitOasis/Coin/Address/BitcoinAddress.php, src/BitOasis/Coin/Address/BitcoinTestnetAddress.php, src/BitOasis/Coin/Address/EosAddress.php, src/BitOasis/Coin/Address/EthereumAddress.php, src/BitOasis/Coin/Address/EthereumClassicAddress.php, src/BitOasis/Coin/Address/LitecoinAddress.php, src/BitOasis/Coin/Address/MoneroAddress.php, src/BitOasis/Coin/Address/RippleAddress.php, src/BitOasis/Coin/Address/StellarAddress.php, src/BitOasis/Coin/Address/TetherAddress.php, src/BitOasis/Coin/Address/ZcashAddress.php, src/BitOasis/Coin/CryptocurrencyAddress.php, tests/unit/BitOasis/Coin/Address/AlgorandAddressTest.php, tests/unit/BitOasis/Coin/Address/BaseBitcoinCashAddressTest.php, tests/unit/BitOasis/Coin/Address/BasicAttentionTokenAddressTest.php, tests/unit/BitOasis/Coin/Address/BitcoinAddressTest.php, tests/unit/BitOasis/Coin/Address/LitecoinAddressTest.php, tests/unit/BitOasis/Coin/Address/MoneroAddressTest.php, tests/unit/BitOasis/Coin/Address/OmiseGoAddressTest.php, tests/unit/BitOasis/Coin/Address/RippleAddressTest.php, tests/unit/BitOasis/Coin/Address/StellarAddressTest.php, tests/unit/BitOasis/Coin/Address/TetherAddressTest.php, tests/unit/BitOasis/Coin/Address/ZcashAddressTest.php, tests/unit/BitOasis/Coin/Address/ZeroXAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/12)
=> BB-1127: Added static handling of address additional ID

src/BitOasis/Coin/Address/BaseMultiProtocolAddress.php, src/BitOasis/Coin/Address/LeoAddress.php, src/BitOasis/Coin/Address/TetherAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/13)
=> Added LEO Token

src/BitOasis/Coin/Address/NeoAddress.php, src/BitOasis/Coin/Address/TezosAddress.php, src/BitOasis/Coin/Address/Validators/NeoAddressValidator.php, src/BitOasis/Coin/Address/Validators/TezosAddressValidator.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/NeoAddressTest.php, tests/unit/BitOasis/Coin/Address/TezosAddressTest.php, tests/unit/BitOasis/Coin/Address/Validators/NeoAddressValidatorTest.php, tests/unit/BitOasis/Coin/Address/Validators/TezosAddressValidatorTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/14)
=> BB-1282, BB-1295: NEO, Tezos

src/BitOasis/Coin/Address/AugurAddress.php, src/BitOasis/Coin/Address/DaiAddress.php, src/BitOasis/Coin/Address/KyberAddress.php, src/BitOasis/Coin/Address/MakerAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/AugurAddressTest.php, tests/unit/BitOasis/Coin/Address/DaiAddressTest.php, tests/unit/BitOasis/Coin/Address/KyberAddressTest.php, tests/unit/BitOasis/Coin/Address/MakerAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/15)
=> BB-1460: Added Augur, Kyber, Dai and Maker coins

src/BitOasis/Coin/Address/BalancerAddress.php, src/BitOasis/Coin/Address/CompoundAddress.php, src/BitOasis/Coin/Address/SynthetixAddress.php, src/BitOasis/Coin/Address/UniswapAddress.php, src/BitOasis/Coin/Address/YearnFinanceAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/BalancerAddressTest.php, tests/unit/BitOasis/Coin/Address/CompoundAddressTest.php, tests/unit/BitOasis/Coin/Address/SynthetixAddressTest.php, tests/unit/BitOasis/Coin/Address/UniswapAddressTest.php, tests/unit/BitOasis/Coin/Address/YearnFinanceAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/17)
=> BB-1644: Added UNI, YFI, BAL, COMP & SNX

src/BitOasis/Coin/Address/DogecoinAddress.php, src/BitOasis/Coin/Address/Validators/DogecoinAddressValidator.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/DogecoinAddressTest.php, tests/unit/BitOasis/Coin/Address/Validators/DogecoinAddressValidatorTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/18)
=> Added Dogecoin

src/BitOasis/Coin/Address/CosmosAddress.php, src/BitOasis/Coin/Address/TerraAddress.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/23)
=> Update LUNA and ATOM tag name to `MEMO`

src/BitOasis/Coin/Utils/Bech32/Bech32.php, tests/unit/BitOasis/Coin/Address/CardanoAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/24)
=> Update BECH32 to allow strings with length up to 110 chars, add test cases for ADA

src/BitOasis/Coin/DefaultCryptocurrencyFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/28)
=> Fix VeChain name

src/BitOasis/Coin/Address/Validators/FilecoinAddressValidator.php, src/BitOasis/Coin/Utils/Strings.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/29)
=> Update filecoin address validation for pecl sodium library

src/BitOasis/Coin/Address/Validators/NeoAddressValidator.php, tests/unit/BitOasis/Coin/Address/NeoAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/31)
=> [TH] Add `N` prefix addresses support for NEO address

src/BitOasis/Coin/CryptocurrencyNetwork.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyNetworkFactory.php, tests/unit/BitOasis/Coin/Address/EthereumPoWAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/38)
=> Add Ethereum POW as separate networks and map ETHW to Ethereum POW network

src/BitOasis/Coin/Address/BitcoinAddress.php, src/BitOasis/Coin/Address/Validators/Bech32AddressValidator.php, src/BitOasis/Coin/Address/Validators/BitcoinBech32AddressValidator.php, src/BitOasis/Coin/Address/Validators/CosmosAddressValidator.php, src/BitOasis/Coin/Address/Validators/DigibyteBech32AddressValidator.php, src/BitOasis/Coin/Address/Validators/ElrondEgoldValidator.php, src/BitOasis/Coin/Address/Validators/IotaAddressValidator.php, src/BitOasis/Coin/Address/Validators/QtumAddressBech32Validator.php, src/BitOasis/Coin/Address/Validators/TerraAddressValidator.php, tests/unit/BitOasis/Coin/Address/BitcoinAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/35)
=> [TH-1737] Add Bech32 addresses support for Bitcoin addresses

src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/40)
=> Remove TRON support for USDT (temporary)

src/BitOasis/Coin/Address/BitcoinAddress.php, src/BitOasis/Coin/Address/EthereumPoWAddress.php, src/BitOasis/Coin/Address/Validators/Bech32AddressValidator.php, src/BitOasis/Coin/Address/Validators/BitcoinBech32AddressValidator.php, src/BitOasis/Coin/Address/Validators/CosmosAddressValidator.php, src/BitOasis/Coin/Address/Validators/DigibyteBech32AddressValidator.php, src/BitOasis/Coin/Address/Validators/ElrondEgoldValidator.php, src/BitOasis/Coin/Address/Validators/IotaAddressValidator.php, src/BitOasis/Coin/Address/Validators/QtumAddressBech32Validator.php, src/BitOasis/Coin/Address/Validators/TerraAddressValidator.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/CryptocurrencyNetwork.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, src/BitOasis/Coin/DefaultCryptocurrencyNetworkFactory.php, tests/unit/BitOasis/Coin/Address/BitcoinAddressTest.php, tests/unit/BitOasis/Coin/Address/EthereumPoWAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/42)
=> Post networks into Master

src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/43)
=> [TH] Enable TRON network for USDT

src/BitOasis/Coin/Address/BitcoinAddress.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/44)
=> [TH-2066] Return BTC bech32 addresses in lowercase format.

src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/45)
=> Enable tron for USDT

src/BitOasis/Coin/Address/TetherGoldAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/TetherGoldAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/46)
=> [TH-2312] Add Tether Gold

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/47)
=> Update .circleci/config.yml to use 2G memory for composer

src/BitOasis/Coin/Address/ArbitrumAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/ArbitrumAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/49)
=> [TH-2396] ARB Listing

src/BitOasis/Coin/Cryptocurrency.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/50)
=> Add OMR / BHD / QAR fiat currencies

src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/52)
=> [TH-2490] Add Jun 2023 currencies

src/BitOasis/Coin/DefaultCryptocurrencyFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/53)
=> [TH] Update SAND and RBTC names

src/BitOasis/Coin/CryptocurrencyNetwork.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/54)
=> Add BTG, RBTC, XDC and SGB networks

src/BitOasis/Coin/CryptocurrencyNetwork.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/55)
=> Update RBTC network name

src/BitOasis/Coin/Address/BitcoinGoldAddress.php, src/BitOasis/Coin/Address/Validators/BitcoinGoldAddressValidator.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyNetworkFactory.php, tests/unit/BitOasis/Coin/Address/BitcoinGoldAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/56)
=> [TH-2501] Add BitcoinGold Address support

src/BitOasis/Coin/Address/LitecoinAddress.php, src/BitOasis/Coin/Address/Validators/LitecoinBech32AddressValidator.php, tests/unit/BitOasis/Coin/Address/LitecoinAddressTest.php
Fix LTC address format where address starts with ltc1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/57)
=> TH-2643 : Fix LTC address format where address starts with ltc1

src/BitOasis/Coin/DefaultCryptocurrencyFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/59)
=> Fix QRDO, FLOKI & SEI Decimals

src/BitOasis/Coin/Address/PolygonEcosystemTokenAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/PolygonEcosystemTokenAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/64)
=> Add Polygon Ecosystem Token

src/BitOasis/Coin/DefaultCryptocurrencyFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/62)
=> OTEAM-3986: Fix Near Decimals

src/BitOasis/Coin/Address/Validators/SolanaAddressValidator.php, tests/unit/BitOasis/Coin/Address/JupiterAddressTest.php, tests/unit/BitOasis/Coin/Address/SolanaAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/65)
=> Update Solana Validator to Validate Off-Curve Addresses

src/BitOasis/Coin/Address/BonkAddress.php, src/BitOasis/Coin/Address/CatInADogsWorldAddress.php, src/BitOasis/Coin/Address/CelestiaAddress.php, src/BitOasis/Coin/Address/EthenaAddress.php, src/BitOasis/Coin/Address/PepeAddress.php, src/BitOasis/Coin/Address/TomiAddress.php, src/BitOasis/Coin/Address/TurboAddress.php, src/BitOasis/Coin/Address/Validators/CelestiaAddressValidator.php, src/BitOasis/Coin/Address/WhiteBitAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/CryptocurrencyNetwork.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, src/BitOasis/Coin/DefaultCryptocurrencyNetworkFactory.php, tests/unit/BitOasis/Coin/Address/BonkAddressTest.php, tests/unit/BitOasis/Coin/Address/CatInADogsWorldAddressTest.php, tests/unit/BitOasis/Coin/Address/CelestiaAddressTest.php, tests/unit/BitOasis/Coin/Address/EthenaAddressTest.php, tests/unit/BitOasis/Coin/Address/PepeAddressTest.php, tests/unit/BitOasis/Coin/Address/TomiAddressTest.php, tests/unit/BitOasis/Coin/Address/TurboAddressTest.php, tests/unit/BitOasis/Coin/Address/WhiteBitAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/68)
=> Add 2024 Q4 Tokens

src/BitOasis/Coin/Address/ApeCoinAddress.php, src/BitOasis/Coin/Address/ArtificialSuperintelligenceAllianceAddress.php, src/BitOasis/Coin/Address/RallyAddress.php, src/BitOasis/Coin/Address/TheSandboxAddress.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/67)
=> OTEAM-4370: Add APE, FET, RLY, SAND Addresses

src/BitOasis/Coin/Address/Validators/CeloAddressValidator.php, src/BitOasis/Coin/Address/Validators/FlareAddressValidator.php, src/BitOasis/Coin/Address/Validators/InjectiveEvmAddressValidator.php, src/BitOasis/Coin/Address/Validators/KavaEvmAddressValidator.php, src/BitOasis/Coin/Address/Validators/SongbirdAddressValidator.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/70)
=> Enforce 0x Prefix for EVM Compatible Addresses

src/BitOasis/Coin/Address/InjectiveAddress.php, tests/unit/BitOasis/Coin/Address/InjectiveAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/71)
=> HOTFIX: Add Memo support for InjectiveAddress

src/BitOasis/Coin/Address/AiozNetworkProtocolAddress.php, src/BitOasis/Coin/Address/AssangeDaoAddress.php, src/BitOasis/Coin/Address/BitKanAddress.php, src/BitOasis/Coin/Address/DataOwnershipProtocolAddress.php, src/BitOasis/Coin/Address/GominingAddress.php, src/BitOasis/Coin/Address/SpectralAddress.php, src/BitOasis/Coin/Address/SweatEconomyAddress.php, src/BitOasis/Coin/Address/VelarAddress.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, tests/unit/BitOasis/Coin/Address/AiozNetworkAddressTest.php, tests/unit/BitOasis/Coin/Address/AssangeDaoAddressTest.php, tests/unit/BitOasis/Coin/Address/BitKanAddressTest.php, tests/unit/BitOasis/Coin/Address/DataOwnershipProtocolAddressTest.php, tests/unit/BitOasis/Coin/Address/GominingAddressTest.php, tests/unit/BitOasis/Coin/Address/SpectralAddressTest.php, tests/unit/BitOasis/Coin/Address/SweatAddressTest.php, tests/unit/BitOasis/Coin/Address/VelarAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/73)
=> OTEAM-4632: Add 2025 Q1 token listing Batch 1

src/BitOasis/Coin/Address/LidoDaoAddress.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, tests/unit/BitOasis/Coin/Address/LidoDaoAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/75)
=> Add LDO address handler

src/BitOasis/Coin/Address/SonicAddress.php, src/BitOasis/Coin/Address/Validators/SonicAddressValidator.php, src/BitOasis/Coin/Cryptocurrency.php, src/BitOasis/Coin/CryptocurrencyNetwork.php, src/BitOasis/Coin/DI/DefaultCurrencyAddressTypes.php, src/BitOasis/Coin/DefaultCryptocurrencyFactory.php, src/BitOasis/Coin/DefaultCryptocurrencyNetworkFactory.php, tests/unit/BitOasis/Coin/Address/SonicAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/76)
=> TAR-93: Sonic Token Listing

src/BitOasis/Coin/Address/SeiAddress.php, tests/unit/BitOasis/Coin/Address/SeiAddressTest.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/80)
=> COV-102: Fix SEI address (Add memo)

src/BitOasis/Coin/DefaultCryptocurrencyFactory.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bit-oasis/coin/81)
=> Fix SEI Decimals
